<?xml version="1.0" encoding="UTF-8"?>
<!--
    SPDX-License-Identifier: Apache-2.0
    Copyright Red Hat Inc. and Hibernate Authors
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.hibernate.validator</groupId>
        <artifactId>hibernate-validator-public-parent</artifactId>
        <version>9.2.0-SNAPSHOT</version>
        <relativePath>../parents/public/pom.xml</relativePath>
    </parent>

    <artifactId>hibernate-validator-china-constraints</artifactId>

    <name>Hibernate Validator China Constraints</name>
    <description>China-specific validation constraints for Hibernate Validator.</description>

    <properties>
        <deploy.skip>false</deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.expressly</groupId>
            <artifactId>expressly</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator-test-utils</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>test</defaultGoal>
        <resources>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
            </resource>
            <resource>
                <directory>${rootProject.directory}</directory>
                <includes>
                    <include>license.txt</include>
                </includes>
                <targetPath>META-INF</targetPath>
            </resource>
        </resources>
    </build>
</project>
